Testacular app - Part 3
altimetrik-onboarding-uy/rlujambio pull request #13
Opened 2017-12-04 17:52 UTC by rlujambio

Pull request for Part 3 of Testacular App

2017-12-05 02:28 UTC, rjulianialtimetrik requested changes

2017-12-05 02:28 UTC, rjulianialtimetrik commented on src/classes/TabsController.cls
>        Database.DeleteResult dr = Database.delete(tc);
Why were all lines below deleted?

2017-12-05 02:28 UTC, rjulianialtimetrik commented on src/classes/TestDetailsController.cls
> +	public static List<Step__c> getSteps(Test_Case__c tc){
Is there any piece of code that gets the order of steps for a test case stored after the users makes a change?

2017-12-05 02:28 UTC, rjulianialtimetrik commented on src/classes/scheduledEmail.cls
> +					Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
This is not processing results properly, since it loops through the query's results inside the execute method, which is limited to 50K records. You should investigate how to do that differently so that your code is able to overcome said limit.

2017-12-05 02:28 UTC, rjulianialtimetrik commented on src/classes/scheduledEmail.cls
> +								List<AggregateResult> queryResult = [SELECT COUNT_DISTINCT(Id) total FROM Test_Case__c WHERE Project__c = : p.Id];
You should build your queries in a smarter way because using queries inside a loop is an anti-pattern.

2017-12-05 02:28 UTC, rjulianialtimetrik commented on src/triggers/notificateOwner.trigger
> +          List<AggregateResult> queryResult = [SELECT COUNT_DISTINCT(Id) total FROM Test_Case__c WHERE Project__c = : p.Id];
Again, using queries inside for-loops is discouraged and overall an anti-pattern that can quickly make you hit some governor limits.

2017-12-05 13:23 UTC, rlujambio commented on src/classes/scheduledEmail.cls
> +								List<AggregateResult> queryResult = [SELECT COUNT_DISTINCT(Id) total FROM Test_Case__c WHERE Project__c = : p.Id];
I put the query outside any loop and then I made a Map <Id, Amount of Test Cases for that Id> in order to accomplish what I wanted.

2017-12-05 13:23 UTC, rlujambio commented on src/triggers/notificateOwner.trigger
> +          List<AggregateResult> queryResult = [SELECT COUNT_DISTINCT(Id) total FROM Test_Case__c WHERE Project__c = : p.Id];
I put the query outside any loop and then I made a Map <Id, Amount of Test Cases for that Id> in order to accomplish what I wanted.

2017-12-06 15:09 UTC, rlujambio commented on src/classes/TabsController.cls
>        Database.DeleteResult dr = Database.delete(tc);
I couldn't make a test case were the delete fails and executes the delete lines. The test fires an exception before that and so the code coverage was not 100%, which was hampering the achievement of 90% of overall coverage. I did it in other controllers, so if you want I can put them back.

2017-12-06 15:16 UTC, rlujambio commented on src/classes/TestDetailsController.cls
> +	public static List<Step__c> getSteps(Test_Case__c tc){
I added a new custom number field in the Step object, named "Order" which tells the order of the step in the collection of a Test Case steps. The I added client and server side logic to handle the behavior of dragging and dropping a step. Yesterday I tried doing this with a custom lookup field called "Next Step". The idea was to hold in this field the Id of the next step. However, the ordering of the elements during the multiple query proved to be so unpredictable, no matter what condition I used (ASC sometimes gave me the "right" order, sometimes not. The same happened with DESC), that I had to drop the idea.

2017-12-06 15:53 UTC, rlujambio commented on src/classes/scheduledEmail.cls
> +					Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
I created a batch process named "emaiBatch" (missing the l, sorry) which is called by the scheduledEmail class. At the start method it returns a custom iterator that I made, based on a new Custom Object named "Email Entry". This object holds all the data requiered to send the emails. In the execute method I only store the mails to send by the finish method in a global variable. Then the finish method sends the emails.

2017-12-06 18:33 UTC, rjulianialtimetrik commented on src/classes/TabsController.cls
>        Database.DeleteResult dr = Database.delete(tc);
Please do put them back. that's more important than the 90% coverage

2017-12-06 18:34 UTC, rjulianialtimetrik commented on src/classes/TestDetailsController.cls
> +	public static List<Step__c> getSteps(Test_Case__c tc){
Sounds good as long as you make sure you show items with the same sequence number taking into account their latest updated date (latest updated for position X goes first in the list)

2017-12-06 18:35 UTC, rjulianialtimetrik commented on src/classes/scheduledEmail.cls
> +					Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
I need to see the solution to understand if it's fine or not

2017-12-06 18:35 UTC, rjulianialtimetrik commented on src/classes/scheduledEmail.cls
> +								List<AggregateResult> queryResult = [SELECT COUNT_DISTINCT(Id) total FROM Test_Case__c WHERE Project__c = : p.Id];
cool

2017-12-06 18:35 UTC, rjulianialtimetrik commented on src/triggers/notificateOwner.trigger
> +          List<AggregateResult> queryResult = [SELECT COUNT_DISTINCT(Id) total FROM Test_Case__c WHERE Project__c = : p.Id];
that's the idea.

2017-12-07 13:55 UTC, rjulianialtimetrik approved these changes

2017-12-07 14:30 UTC, merged